"""Generate the standalone build-along course from the tested source files.
Run from the repository: python3 tool/build_handbook.py
No third-party Python modules, network, or repository access needed by the reader.
"""
from pathlib import Path
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parent / 'LuxeStays-Build-Handbook.html'
chapters = []
included = set()

def code(text, label='Terminal', path=None):
    attr = f' data-source="{html.escape(path)}"' if path else ''
    return f'<figure><figcaption>{html.escape(label)} <button type="button" class="copy">Copy</button></figcaption><pre><code{attr}>{html.escape(text)}</code></pre></figure>'

def source(path):
    included.add(path)
    text = (ROOT / path).read_text()
    comments = re.findall(r'^/// ?(.*)', text, re.M)
    intro = ' '.join(comments[:5]).strip()
    if not intro:
        intro = 'This file implements ' + Path(path).stem.replace('_', ' ') + '. Read the imports first to see which earlier pieces it connects.'
    classes = re.findall(r'^(?:abstract |final |sealed )*class (\w+)|^enum (\w+)', text, re.M)
    names = ', '.join(a or b for a,b in classes)
    return (f'<section class="lesson"><h3>Create or replace <code>{path}</code></h3>'
        f'<p>{html.escape(intro)}</p><p>Create its parent folders if necessary. The block is the complete file; replace the whole file rather than appending a second class.</p>'
        + (f'<p><strong>Reading guide:</strong> {html.escape(names)} are the named types introduced here. Constructor parameters supply their inputs; fields hold their values; methods perform the operations. Read one method at a time and follow the comments inside it.</p>' if names else '')
        + code(text, path + ' — complete file', path)
        + '<p class="tip">Save before continuing. If an import is red, check spelling and finish the files in this stage before running its checkpoint. Format after each file to catch missing brackets early.</p></section>')

def sources(paths):
    return ''.join(source(p) for p in paths)

def glob(pattern):
    return [str(p.relative_to(ROOT)) for p in sorted(ROOT.glob(pattern)) if str(p.relative_to(ROOT)) not in included]

def chapter(title, goal, concepts, body='', files=(), verify='fvm flutter analyze', checkpoint='', trouble='If analysis fails, read the first error, check its file path, and compare the complete block before continuing.'):
    n = len(chapters)+1
    text = f'<article id="stage-{n}"><p class="eyebrow">Stage {n:02d}</p><h2>{title}</h2><p class="objective"><strong>Objective:</strong> {goal}</p><p><strong>Prerequisite:</strong> '+ ('No previous Flutter knowledge. A computer with internet and enough space for the mobile SDKs.' if n==1 else f'Complete stage {n-1} and save its checkpoint.') + f'</p><h3>Understand before typing</h3>{concepts}{body}{sources(files)}<h3>Run and verify</h3>{code(verify)}<aside><strong>Troubleshooting.</strong> {trouble}</aside><p class="checkpoint"><strong>Checkpoint:</strong> {checkpoint or goal}</p><a href="#contents">Back to course map ↑</a></article>'
    chapters.append((title,text))

chapter('Meet LuxeStays', 'Understand the guest journey and the proof-of-concept boundary.',
    '<p>A guest searches a destination, selects dates and a room, adds it to a cart, enters guest details, authorizes a simulated payment and receives a reservation. Members can explore discounts and points. A mock server is a small program pretending to be remote services, so you can learn without paid accounts.</p><p>Flutter builds the screens. Dart is the programming language used for both app and mock. A WebView is an embedded browser for a hosted page. A repository combines data sources; a client sends HTTP requests to one service.</p>',
    '<div class="diagram">Guest → Flutter screen → state controller → repository → API client → local mock<br>Hosted payment page → bridge hint → server verification → reservation</div><aside>The shopping gateway is application-owned. Public SynXis Property Hub has a different retrieval API. We implement that subset separately and label all assumptions. This is not a production booking system.</aside>',
    verify='No command yet. Read the journey above.', checkpoint='You can explain which process draws the app and which serves the mock data.')
chapter('Install a reproducible toolchain', 'Prepare Flutter 3.47.4 / Dart 3.13.3 and a mobile emulator.',
    '<p>An SDK is a software development kit: compiler, libraries and command-line tools. Flutter includes Dart; do not install an unrelated Dart version. FVM is an optional SDK version manager used in this course to keep the project and CI on the same version.</p><ol><li>Follow <a href="https://docs.flutter.dev/install">Flutter installation</a> for your OS. Add Flutter to PATH so the terminal can find it.</li><li>Install Android Studio, its Android SDK and emulator, then create and boot a virtual phone. Accept the SDK licenses yourself with <code>flutter doctor --android-licenses</code>.</li><li>For iOS you need macOS and Xcode. Open Xcode once, install a simulator runtime and complete its first-launch setup. Install CocoaPods for this project’s plugin integration.</li><li>Install VS Code plus the Flutter extension (it includes Dart support). Open your project folder, not just a Dart file.</li></ol>',
    code('dart pub global activate fvm\nfvm install 3.47.4\nflutter doctor -v'),
    verify='flutter devices', checkpoint='A running Android emulator or iOS simulator is listed. Missing license/toolchain entries are resolved before mobile builds.', trouble='If fvm is not found, add your Dart pub-cache bin directory to PATH and reopen the terminal. Windows/Linux cannot build iOS. An SDK download may take several minutes.')
chapter('Create an empty project', 'Create generated platform hosts and run the counter app once.',
    '<p>The project folder contains <code>lib</code> for Dart source, <code>test</code> for tests, and <code>android</code>/<code>ios</code> for native hosts. <code>pubspec.yaml</code> lists packages. A package is a reusable library. The lockfile records exact resolved versions.</p>',
    code('mkdir luxe_course\ncd luxe_course\nfvm use 3.47.4 --force\nfvm flutter create --project-name luxe_stays --org com.luxestays --platforms android,ios,web .\nfvm flutter run'),
    verify='fvm flutter test', checkpoint='The generated counter app runs and its generated widget test passes. All later paths are relative to this new folder.', trouble='Do not create this practice folder inside the existing luxe_stays project. Use a separate workspace. Stop a running app with q in its terminal.')
chapter('Learn the Dart you need', 'Read values, classes, null safety and asynchronous code.',
    '<p><code>final</code> assigns a value once; <code>const</code> creates a compile-time constant. <code>String?</code> may hold text or null (no value). Use <code>??</code> for a default, and only use <code>!</code> when code has proved a value exists. A class groups values and behavior. An underscore makes a Dart member private to its library. In Dart 3.13 a named initializing parameter like <code>this._logger</code> has the public call-site name <code>logger:</code>; use the pinned SDK to support this syntax. Named parameters make calls readable. A List is an ordered collection; a Map associates keys with values.</p><p>A <code>Future&lt;T&gt;</code> promises one later result. <code>await</code> pauses that function without blocking the screen. A Stream delivers multiple events over time. <code>try/catch</code> handles exceptions. The app also uses Result values so expected failures can be displayed deliberately.</p>',
    code("Future<void> main() async {\n  const hotel = 'Luxe Paris';\n  final prices = <int>[32000, 32000, 38000, 0];\n  final total = prices.fold<int>(0, (sum, price) => sum + price);\n  await Future<void>.delayed(const Duration(milliseconds: 20));\n  print('$hotel: ${total / 100} USD before tax');\n}\n", 'Create tool/scratch.dart — temporary exercise'),
    verify='fvm dart run tool/scratch.dart', checkpoint='The terminal prints Luxe Paris: 1020.0 USD before tax. Delete tool/scratch.dart after this exercise.', trouble='Dollar interpolation belongs inside a Dart string. Amounts here are integer cents to avoid floating-point rounding in totals.')
chapter('Declare packages and lint rules', 'Install only the packages used by the app and server.',
    '<p>Riverpod stores state and supplies dependencies. Dio handles HTTP requests. webview_flutter embeds native browsers. cached_network_image caches images. flutter_secure_storage stores issued tokens. crypto supports PKCE challenges. Shelf and shelf_router run the local server. mocktail helps isolate code under test. Lints are static checks that catch common mistakes before running.</p><p>A caret allows compatible package releases; the lockfile pins one tested resolution. SDK packages have no independent version. Never copy real credentials into YAML.</p>',
    files=['pubspec.yaml','analysis_options.yaml','.fvmrc','.gitignore'], verify='fvm flutter pub get', checkpoint='Dependencies resolve. Keep the new pubspec.lock under source control. A reference lockfile is included in the final reproducibility appendix.', trouble='YAML uses spaces, not tabs. Dependencies and dev_dependencies are top-level sections. An incompatible SDK error means you are not using the pinned Flutter version.')
mini="""import 'package:flutter/material.dart';
void main() => runApp(const MaterialApp(home: Welcome()));
class Welcome extends StatelessWidget {
  const Welcome({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text('LuxeStays')),
    body: const SafeArea(child: Center(child: Text('Find your next stay'))),
  );
}
"""
chapter('Build your first app shell', 'Replace the counter with a small hotel welcome screen.',
    '<p>A widget describes part of the screen. <code>build</code> returns that description. MaterialApp supplies navigation and theme. Scaffold gives a page an app bar and body. SafeArea avoids system cutouts. StatelessWidget has no changing internal state. Hot reload updates most code while the app runs; a full restart is needed after changing startup configuration.</p>',
    '<p>Delete the generated <code>test/widget_test.dart</code>, which refers to the old counter. Replace <code>lib/main.dart</code> with this complete temporary shell.</p>'+code(mini,'lib/main.dart — temporary complete replacement'),
    verify='fvm flutter run', checkpoint='You see LuxeStays and Find your next stay. Keep this main.dart until the course explicitly replaces it.')
chapter('Add a theme and reusable widgets', 'Build visual consistency before adding networking.',
    '<p>A theme shares colors and typography. Padding gives content space; Row lays children side by side; Column stacks them. Expanded takes remaining space. ListView scrolls. A reusable widget accepts inputs instead of reaching into unrelated app state. Text labels and semantic descriptions help screen readers.</p>',
    files=['lib/app/theme.dart','lib/shared/widgets/app_panel.dart','lib/shared/widgets/section_heading.dart','lib/shared/widgets/app_snack_bar.dart'],
    body='<p>After creating the files below, modify the temporary main.dart: add <code>import \'app/theme.dart\';</code> and change <code>const MaterialApp(home: Welcome())</code> to <code>MaterialApp(theme: AppTheme.light(), darkTheme: AppTheme.dark(), home: const Welcome())</code>. Removing the outer const is necessary because the theme is built at runtime.</p>', verify='fvm flutter analyze\nfvm flutter run', checkpoint='The welcome page uses the LuxeStays palette. Try light/dark mode and large system text.')
chapter('Represent failure and money', 'Introduce small shared types that can be tested without a screen.',
    '<p>Money stores minor units (cents for USD). A Failure carries a user-facing message and a diagnostic description. A sealed Result is either Ok(data) or Err(failure). Mapping transforms a successful result while preserving failure. These types stop raw network exceptions and floating-point prices spreading through widgets.</p>',
    files=['lib/core/error/failure.dart','lib/core/result.dart','lib/core/utils/money.dart','lib/core/utils/date_x.dart','lib/core/utils/ids.dart','lib/core/logging/app_logger.dart','lib/core/analytics/analytics.dart','lib/shared/widgets/app_states.dart'],
    verify='fvm dart analyze lib/core lib/shared',checkpoint='Shared code analyzes. The welcome UI remains usable while you build the foundations.', trouble='Create all files in this stage before analyzing: Result imports Failure, and analytics imports the logger. No network is involved yet.')
chapter('Model guests, rooms and reservations', 'Create immutable domain objects.',
    '<p>Domain means the hotel business concepts rather than screen or HTTP details. A stay contains arrival/departure; occupancy contains adults and child ages; an offer combines room, rate and dates. <code>copyWith</code> returns a changed copy, allowing state updates without mutating a value shared elsewhere.</p><p>Read the small search/media/hotel types first, then rate, loyalty, cart and booking. Notice how totals derive from nightly prices. Never rename a currency without converting its numeric value; this demo uses USD.</p>',
    files=['lib/domain/search.dart','lib/domain/media.dart','lib/domain/hotel.dart','lib/domain/rate.dart','lib/domain/loyalty.dart','lib/domain/cart.dart','lib/domain/booking.dart'],verify='fvm dart analyze lib/domain',checkpoint='The app can describe a booking independently of its UI or provider payloads.')
chapter('Configure requests and token storage', 'Build one consistent HTTP boundary.',
    '<p>Configuration supplies public URLs and identifiers through <code>--dart-define</code>. These are compiled into the binary and are not secret storage. A token is a temporary credential issued after authentication; store it in platform secure storage. PKCE is a proof used during OAuth login, explained when identity is connected.</p><p>An interceptor runs around an HTTP request: attach a correlation ID, add an issued token, log redacted diagnostics, or retry a transient failure. GET can be retried safely. A booking POST needs a server-supported replay guarantee; our demo idempotency key is not a claim about SynXis.</p>',
    files=['lib/core/config/app_config.dart','lib/core/storage/token_store.dart','lib/core/error/error_mapper.dart']+glob('lib/core/network/**/*.dart'),verify='fvm dart analyze lib/core',checkpoint='The request layer compiles with bounded timeouts and typed error mapping.',trouble='Use full URLs including http:// for local development. Never put provider secrets in dart-defines. The server will be introduced next; connection failures are expected until it runs.')
chapter('Create your local mock services', 'Run the server before wiring it to screens.',
    '<p>HTTP pairs a method and path with a request body, headers and status code. JSON is text containing objects, arrays and primitive values. Shelf turns a Dart function into a request handler. The Router matches paths. Fixtures are fictional data. Begin with support/fixtures/png, then each route file, web pages, and server.dart last.</p><p>Each file below is a separate lesson. Read one route at a time: input → validation → state change → response. A process restart resets reservations, quotes, points and payments. The mock is suitable for trusted local development only.</p>',
    files=['tool/mock_server/support.dart','tool/mock_server/fixtures.dart','tool/mock_server/png.dart','tool/mock_server/web_pages.dart','tool/mock_server/payment_routes.dart','tool/mock_server/synxis_routes.dart','tool/mock_server/property_hub_routes.dart','tool/mock_server/cms_routes.dart','tool/mock_server/salesforce_routes.dart','tool/mock_server/leonardo_routes.dart','tool/mock_server/server.dart'],
    verify='fvm dart run tool/mock_server/server.dart\n# In a SECOND terminal:\ncurl http://localhost:8080/health',checkpoint='Health returns status ok and a hotel count. Leave this terminal running.',trouble='Address already in use means another process owns port 8080. Stop your previous server or choose --port 8081 and use that port in every URL. Do not run two commands sequentially in the server terminal: the server intentionally keeps running.')
chapter('Decode and verify the booking gateway', 'Connect domain offers to the demo JSON contract.',
    '<p>A DTO (data-transfer object) mirrors one response format. Its fromJson constructor checks fields. A mapper converts that DTO into domain data. SynxisApi is retained as the adapter name, but its shopping/create/cancel shapes are local BFF assumptions. Property Hub retrieval uses separate lower-camelCase fields and integer IDs.</p><p>The quote store keeps the original nightly prices and promotion; re-quote compares totals before payment. Idempotency means a repeated operation has one effect. The reservation route rejects a reused key with a changed body.</p>',
    files=glob('lib/integrations/synxis/*.dart'),verify='fvm dart analyze lib/integrations/synxis',checkpoint='The booking client and mappers compile. No live SynXis credentials are required.',trouble='Do not substitute a SynXis production URL. Read the API audit in the final chapter before adapting any real provider.')
chapter('Enrich content and images', 'Add editorial content and licensed-media abstractions.',
    '<p>Contentful entries have fields and references; included assets resolve linked images. This app uses REST, not GraphQL. Leonardo Worldwide is hospitality media management. Leonardo.Ai is a different product; its optional legacy-shaped demo is not a current production integration.</p><p>A repository may cache data or tolerate missing editorial content. The hotel can still be bookable if its marketing headline is unavailable. A media provider returns an appropriate rendition for the displayed size; the mock serves gradients rather than external photography.</p>',
    files=glob('lib/integrations/cms/*.dart')+glob('lib/integrations/leonardo/*.dart'),verify='fvm dart analyze lib/integrations/cms lib/integrations/leonardo',checkpoint='Content and media adapters compile. Images in the mock work without internet access.')
chapter('Add identity, rewards and payments', 'Model member state and hosted payment intents.',
    '<p>OAuth authorizes access without giving the app a provider password. PKCE binds the authorization callback to the initiating client. The sample membership sign-in bypass is for mocks only. Loyalty points and voucher processes are fictional program rules; a real Salesforce org determines its fields, processes and API version.</p><p>A payment intent is a reference to a payment attempt. The hosted page returns a hint; the app verifies its status through the BFF. The demo collects no real card data and makes no PCI compliance claim.</p>',
    files=glob('lib/integrations/salesforce/*.dart')+glob('lib/integrations/payments/*.dart'),verify='fvm dart analyze lib/integrations',checkpoint='All integration clients compile and remain replaceable behind their repositories.')
chapter('Compose repositories and state', 'Connect dependencies and introduce Riverpod gradually.',
    '<p>Dependency injection means supplying collaborators rather than creating hidden global instances. A Provider constructs a service. <code>ref.watch</code> subscribes to changes; <code>ref.read</code> takes its current value; <code>ref.onDispose</code> closes resources. A Notifier stores state and exposes actions. An AsyncValue is loading, data or error.</p><p>The hotel repository combines inventory, content and media. BookingRepository coordinates re-quote, payment verification and booking. The search controller uses a request counter so a slow old response cannot overwrite a newer search. Build services first, then the composition root, then controllers.</p>',
    files=glob('lib/data/*.dart')+['lib/app/providers.dart','lib/features/account/session_controller.dart','lib/features/cart/cart_controller.dart','lib/features/search/search_controller.dart','lib/features/home/offers_provider.dart','lib/features/hotel/hotel_detail_controller.dart','lib/features/booking/checkout_controller.dart'],verify='fvm dart analyze lib',checkpoint='All services and controllers compile; the small welcome screen still runs.',trouble='Riverpod 3 removed older exported family type names. Keep inferred family provider declarations as shown. State mutation during build is avoided by the scheduled first search.')
# Put route types in place without importing unfinished screens.
router=(ROOT/'lib/app/router.dart').read_text()
start=router.index('abstract final class Routes')
end=router.index('/// Why Navigator')
route_types="import '../domain/search.dart';\n\n"+router[start:end]
chapter('Build search controls and cards', 'Make destination/date/filter results reusable.',
    '<p>Controlled widgets receive a value and a callback instead of hiding search state. HotelCard displays an offer and invokes onAdd; the parent decides how to change the cart. A bottom sheet is a temporary panel for filters. A date picker returns a value asynchronously; check the widget is still mounted before updating it.</p>',
    code(route_types,'lib/app/router.dart — temporary complete route names and argument types')+'<p>This temporary file supplies route names without importing unfinished screens. We add route destinations later. First create the widgets below.</p>',
    files=['lib/shared/widgets/media_image.dart']+glob('lib/features/search/widgets/*.dart'),verify='fvm dart analyze lib',checkpoint='Cards, stay selector, filters and offers strip compile independently. They will appear when the search screen is connected.')
# temporary app per screen can use final search (router types enough) and simple home; interactions routes not yet wired explained
preview="""import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app/theme.dart';
import 'features/search/search_screen.dart';
void main() => runApp(ProviderScope(child: MaterialApp(
  theme: AppTheme.light(), home: const SearchScreen(),
)));
"""
chapter('Show real mock-backed search results', 'Replace the welcome page with a working search.',
    '<p>ConsumerWidget can read provider state while building. The search page watches SearchState, shows a loading skeleton, then results or a retry message. Rebuilding is Flutter’s normal way to update the display; do not manually repaint widgets.</p>',
    code(preview,'lib/main.dart — complete search preview replacement')+'<p>At this checkpoint search, filters and adding a room work. Named navigation targets are added in the next stage; do not tap cart/detail links yet.</p>',files=['lib/features/search/search_screen.dart','Makefile'],
    verify='make run-emulator\n# iOS simulator instead: make run HOST=localhost',checkpoint='Search results load from the local server. Change dates to four nights and filter rooms.',trouble='Android emulator uses 10.0.2.2 for your computer. localhost means the phone itself unless adb reverse is configured. Changing dart-defines requires a full stop/restart, not hot reload.')
chapter('Build detail, cart and rewards pages', 'Give the search actions destinations.',
    '<p>A route is a page on a navigation stack. Arguments carry the hotel ID and name. Detail uses a family provider so each hotel loads independently. The cart stores selected offers, exposes totals and supports removal. Rewards show member balances and benefits. A page is composed from the same panels and states you already built.</p>',
    files=['lib/features/hotel/hotel_detail_screen.dart','lib/features/cart/cart_screen.dart','lib/features/loyalty/loyalty_screen.dart'],
    verify='fvm dart analyze lib',checkpoint='The three pages compile. Complete the WebView and checkout stages before switching to the full router.',trouble='These screen classes use route names already defined in the temporary router. The final route table comes after all destination classes exist.')
chapter('Connect safe hosted WebViews', 'Embed pages with a typed message bridge.',
    '<p>The JavaScript channel carries text; decode and validate it before using it. A bridge message names a type and payload. A stream emits successive bridge events. Deduplication prevents double handling. Navigation is limited to configured HTTP(S) origins and selected app deep links. A deep link uses a custom URL scheme, such as luxestays://payment-success.</p><p>A page-reported payment success is not proof of payment. The controller checks the expected intent and asks the server. A real provider may require system-browser authentication or additional trusted redirect origins. Never allow every URL to make a demo work.</p>',
    files=glob('lib/webview/bridge/*.dart')+['lib/webview/hybrid_webview.dart','lib/webview/payment_webview_screen.dart','lib/webview/booking_engine_webview_screen.dart','lib/webview/cms_content_webview_screen.dart'],verify='fvm dart analyze lib/webview',checkpoint='The native WebView integration compiles. It runs on Android/iOS; browser-only Flutter web is not a substitute for testing these pages.')
chapter('Finish checkout and navigation', 'Complete search → cart → hosted authorization → confirmation.',
    '<p>A Form groups validated inputs. Validation runs before creating payment. Await each transaction step in order. The controller rejects concurrent starts and mismatched completion hints. Total booking failure requests a demo authorization void; an uncertain void must be reported honestly.</p><p>Create checkout and confirmation first. Then replace the temporary router and main.dart with their final versions. AppRouter now imports every real destination. The final entry point installs error hooks and creates the provider container.</p>',
    files=['lib/features/booking/checkout_screen.dart','lib/features/booking/confirmation_screen.dart','lib/app/router.dart','lib/app/app.dart','lib/main.dart'],verify='fvm flutter analyze\nmake run-emulator',checkpoint='The complete native app can navigate from search to confirmation using synthetic guest/payment data.',trouble='If checkout reports changed prices, search again for a fresh offer. Restarting the server invalidates in-memory quotes. Never enter real card or guest information in this mock.')
chapter('Rehearse loading, failure and accessibility', 'Make the experience usable when services or layouts vary.',
    '<p>Loading is temporary, empty is a valid result, and failure offers recovery. Keep these distinct. Retry lets a guest recover after restoring the network. Errors should explain the action the guest can take without exposing raw payloads. An accessibility label explains an icon or image; a tooltip helps identify an action.</p><ol><li>Search an unavailable destination or an occupancy larger than every room; confirm an empty result.</li><li>Stop the server, search, then restart and retry.</li><li>Use 200% text scaling, a small phone, landscape and a screen reader. Scroll to all checkout fields and actions.</li><li>Check light/dark text contrast and clear field labels. Native WebView accessibility also needs a device pass.</li></ol>',
    code('fvm dart run tool/mock_server/server.dart --latency 25000\n# Or restart with intermittent faults:\nfvm dart run tool/mock_server/server.dart --fail-rate 0.15'),verify='fvm flutter analyze',checkpoint='You can explain and demonstrate loading, empty and error recovery states. This manual pass does not constitute a full accessibility certification.')
chapter('Add automated regression tests', 'Protect behavior instead of only checking compilation.',
    '<p>A unit test checks a small behavior, a widget test renders Flutter widgets in a test environment, and an integration test runs on a device. A test sets up inputs, performs an action and asserts the outcome. Overrides supply predictable dependencies. Mock contract tests validate our gateway behavior; they cannot detect a vendor change without updated official evidence.</p><p>Add core and model tests first, then controller/widget/bridge tests, then the booking lifecycle test. The four-night test protects the re-quote regression and verifies idempotency, authorization and cancellation. The device test exercises real app wiring.</p>',
    files=glob('test/**/*.dart')+glob('integration_test/*.dart')+['tool/contract_check.sh'],verify='fvm flutter test\nbash tool/contract_check.sh http://localhost:8080\nmake integration HOST=10.0.2.2',checkpoint='Local tests pass, then device integration tests run against the server.',trouble='Do not use pumpAndSettle as a substitute for waiting for an external page. Give network-driven assertions a bounded wait. Device failures need emulator logs, not just rerunning a unit test.')
chapter('Build Android and iOS', 'Create reproducible native artifacts with the required host settings.',
    '<p>Flutter generates the native host at project creation. Apply the complete host files below to reproduce the reviewed settings. Android uses Java/Kotlin/Gradle; iOS uses Xcode and CocoaPods here. Debug HTTP settings allow local mocks. A debug-signed artifact is not ready for store distribution. iOS simulator builds need no Apple signing account.</p><p>For local Android JDK compatibility use the Java version reported by flutter doctor and supported by the generated Gradle wrapper. The deployment target must satisfy the plugins. Do not blanket-disable TLS checks to fix a network error.</p>',
    files=[p for p in ['android/gradlew','android/gradlew.bat','android/settings.gradle.kts','android/build.gradle.kts','android/gradle.properties','android/gradle/wrapper/gradle-wrapper.properties','android/app/build.gradle.kts','android/app/src/main/AndroidManifest.xml','android/app/src/debug/AndroidManifest.xml','android/app/src/main/res/xml/network_security_config.xml','ios/Podfile','ios/Runner/Info.plist','tool/patch_platforms.sh','.github/workflows/ci.yml'] if (ROOT/p).exists()],
    verify='fvm flutter pub get\nfvm dart format lib test tool integration_test\nfvm flutter analyze --fatal-infos\nfvm flutter test\nfvm flutter build apk --debug\nfvm flutter build ios --simulator --debug',checkpoint='Build artifacts are produced, or a specific toolchain limitation is recorded. CI runs the same pinned SDK checks.',trouble='Android SDK license acceptance is your decision; run the doctor command interactively. On non-macOS skip iOS builds and use a Mac CI runner. Review the implementation report for this machine’s actual build outcomes.')
chapter('Review architecture, assumptions and job evidence', 'Know exactly what this proof of concept demonstrates.',
    '<p>The final tree separates <code>features</code> (screens/controllers), <code>domain</code> (business values), <code>data</code> (orchestration), <code>integrations</code> (provider adapters), <code>core</code> (shared infrastructure) and <code>webview</code> (hybrid boundary). This is sufficient for this app; adding architectural layers without a need would make learning and maintenance harder.</p>',
    '<div class="diagram">features → data → integrations → core<br>domain supplies shared hotel values<br>app/providers connects the graph<br>tool/mock_server supplies independent demo services</div>'+code('\n'.join(sorted(str(p.relative_to(ROOT)) for p in ROOT.glob('lib/**/*.dart'))),'Final lib/ structure'),
    files=['docs/15-API-AUDIT.md','docs/16-JOB-REQUIREMENTS.md','docs/17-IMPLEMENTATION-REPORT.md'],verify='Review the audit and demonstrate the script in the job-requirements table.',checkpoint='You can distinguish working code, tested mock assumptions and production work still needed.')
chapter('Reproducibility, glossary and final checklist', 'Finish with a source-complete, reviewable application.',
    '<p>The lockfile below records the tested package resolution. After the earlier package install, replace your lockfile with this reference and run pub get again. Additional checked-in documentation and host files are included below for exact reproduction.</p>',
    files=['pubspec.lock']+[p for p in ['ios/Runner.xcodeproj/project.pbxproj','ios/Runner/AppDelegate.swift','ios/Runner/SceneDelegate.swift','ios/Flutter/AppFrameworkInfo.plist','ios/Runner/Runner.entitlements','.env.example','README.md'] if (ROOT/p).exists()],
    verify='fvm flutter pub get\nfvm dart format --output=none --set-exit-if-changed lib test tool integration_test\nfvm flutter analyze --fatal-infos\nfvm flutter test',checkpoint='Keep the app and lockfile in version control, document your device checks, and review all known limitations before presenting the POC.')
assert not set(glob('lib/**/*.dart')), 'Missing app sources: '+str(glob('lib/**/*.dart'))
assert not set(glob('tool/mock_server/*.dart')), 'Missing mock sources'

style='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f8f5ef;color:#252a2c;font:17px/1.7 system-ui,-apple-system,sans-serif}header{background:#153d40;color:#fff;padding:64px max(24px,calc((100vw - 1080px)/2))}header h1{font:clamp(38px,6vw,72px)/1.05 Georgia,serif;max-width:850px;margin:12px 0 24px}header p{max-width:760px;color:#d2e8e3}.eyebrow{font-size:12px;letter-spacing:.2em;text-transform:uppercase;color:#92713f;font-weight:750}header .eyebrow{color:#e8c998}main{max-width:1080px;margin:auto;padding:24px}nav{padding:24px;background:#fff;border:1px solid #d6ded9}nav ol{columns:2;column-gap:44px}nav li{break-inside:avoid;margin:0 0 9px}a{color:#146568}article{scroll-margin-top:18px;padding:48px 0;border-bottom:1px solid #c8d3ce}h2{font:38px/1.2 Georgia,serif;color:#163e40;max-width:850px}h3{font-size:21px;margin-top:30px}p,li{max-width:88ch}.objective{font-size:20px}aside,.tip,.checkpoint{background:#edf2ef;border-left:4px solid #417b70;padding:15px 20px;margin:20px 0}aside{background:#fff0d8;border-color:#b98530}.checkpoint{background:#e4efe9}.diagram{padding:28px;border:1px solid #9cb6aa;background:#fff;font-family:ui-monospace,monospace;line-height:2}.lesson{margin:36px 0;padding-bottom:10px}figure{margin:24px 0;border:1px solid #cbd4cf;border-radius:8px;overflow:hidden;background:#fff}figcaption{padding:10px 16px;background:#e6ece8;font:13px/1.5 ui-monospace,monospace;display:flex;justify-content:space-between;align-items:center;gap:16px;overflow-wrap:anywhere}button{border:1px solid #728e82;background:white;color:#153d40;padding:7px 14px;cursor:pointer;border-radius:4px}button:focus-visible,a:focus-visible{outline:3px solid #b67924;outline-offset:3px}pre{margin:0;padding:20px;overflow:auto;max-height:640px;font:13px/1.65 ui-monospace,SFMono-Regular,Consolas,monospace;tab-size:2}p code,li code{font-size:.86em;background:#e8ece6;padding:2px 4px;overflow-wrap:anywhere}.kw{color:#6e3888}.str{color:#976017}.com{color:#637970}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #ccd5ce;padding:12px}footer{padding:40px 24px;text-align:center;color:#526762}@media(max-width:650px){main{padding:16px}nav ol{columns:1}h2{font-size:30px}header{padding:44px 24px}pre{font-size:12px}figcaption{align-items:flex-start}}@media print{body{background:white;font-size:11pt}nav ol{columns:2}button{display:none}pre{max-height:none;white-space:pre-wrap;font-size:8pt}article{break-before:page}header{background:white;color:black}header p{color:black}}'''
glossary={'Widget':'A description of one part of the screen.','State':'Values that can change and affect the screen.','BuildContext':'The location of a widget in the widget tree.','Mounted':'A widget/provider is still alive; check after asynchronous work before using it.','Future':'One result available later.','Stream':'A sequence of events over time.','Provider':'A Riverpod definition that supplies a service or state.','Notifier':'An object exposing state and actions that replace it.','Repository':'A boundary that combines business-facing data operations.','DTO':'A type matching a serialized request or response.','JSON':'Text encoding for objects, lists and simple values.','HTTP status':'A numeric result: 200 success, 400 bad input, 401 unauthenticated, 403 forbidden, 404 missing, 409 conflict, 422 invalid fields, 503 unavailable.','Idempotency':'Repeating an operation has the same effect as doing it once.','BFF':'Backend for frontend: the application server mediating vendor systems.','CRS / PMS':'Central reservation system / property management system; their APIs serve different purposes.','Rate plan':'Pricing rules and benefits associated with a room offer.','Quote':'A priced offer for particular dates and occupancy.','Authorization':'A payment hold/approval, distinct from capturing funds.','Void':'Cancellation of an authorization.','WebView':'A native embedded browser.','Bridge':'Validated communication between web content and Dart.','Origin':'URL scheme, host and port used to define a web trust boundary.','PKCE':'Proof Key for Code Exchange; binds an OAuth authorization flow to its initiator.','Fixture':'Controlled test data.','Regression':'A defect in behavior that previously worked.','CI':'Continuous integration: automatic checks of committed changes.'}
end='<section id="glossary"><h2>Glossary</h2><dl>'+''.join(f'<dt><strong>{html.escape(k)}</strong></dt><dd>{html.escape(v)}</dd>' for k,v in glossary.items())+'</dl></section><section id="checklist"><h2>Final learner checklist</h2><ul>'+''.join('<li>'+s+'</li>' for s in ['Use the pinned Flutter and Dart versions and commit the regenerated lockfile.','Start mocks without vendor credentials; finish search, room selection, cart and simulated payment.','Verify four-night promotional prices survive re-quote.','Demonstrate error, empty and retry states and rejection of invalid reservations.','Run unit, widget, mock lifecycle and device integration tests.','Build Android and iOS where the host supports them; record exact limitations.','Check large text, small screen, dark mode and screen-reader navigation.','Keep secrets and real payment/guest data out of code and logs.','Explain the separate public Property Hub contract and all demo gateway assumptions.','Describe the job-ad traceability and production work still required.'])+'</ul><p>Future work: implement contracted provider adapters, durable server-side checkout and reconciliation, real identity, licensed images, stronger end-to-end accessibility/performance coverage, release signing and store distribution. The optional AI illustration adapter needs a separately verified current model contract before live use.</p></section>'
end += '<section id="sources"><h2>Official references</h2><p>Checked 14 September 2026. The SynXis overview could not be fetched; the linked public specification was read successfully.</p><ul><li><a href="https://docs.flutter.dev/install/archive">Flutter SDK archive</a></li><li><a href="https://developer.synxis.com/pms/property_hub/reservation/reference-documentation">SynXis Property Hub reference</a> · <a href="https://developer.synxis.com/sites/default/files/public/apidoc_specs/sphReservation4.29.0.yaml">4.29.0 OpenAPI specification</a></li><li><a href="https://www.contentful.com/developers/docs/references/content-delivery-api/links/">Contentful entry and asset links</a></li><li><a href="https://developer.salesforce.com/docs/industries/loyalty/guide/get-started.html">Salesforce Loyalty integration guide</a></li><li><a href="https://docs.leonardo.ai/reference/creategeneration">Current Leonardo.Ai generation reference</a></li></ul></section>'
# Highlight on load while keeping raw code text and clipboard faithful to source.
script=r'''document.querySelectorAll('.copy').forEach(b=>b.addEventListener('click',async()=>{const text=b.closest('figure').querySelector('code').textContent;try{await navigator.clipboard.writeText(text);b.textContent='Copied'}catch{const r=document.createRange();r.selectNodeContents(b.closest('figure').querySelector('code'));const s=window.getSelection();s.removeAllRanges();s.addRange(r);b.textContent='Selected — copy manually'}}));
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
document.querySelectorAll('pre code').forEach(el=>{const t=el.textContent;const re=/(\/\/[^\n]*|'(?:[^'\\]|\\.)*'|\b(?:class|final|const|return|void|import|async|await|if|else|switch|required|super|this|extends|implements|enum|sealed)\b)/g;let at=0,out='',m;while((m=re.exec(t))){out+=esc(t.slice(at,m.index));let cls=m[0].startsWith('//')?'com':m[0].startsWith("'")?'str':'kw';out+='<span class="'+cls+'">'+esc(m[0])+'</span>';at=re.lastIndex}el.innerHTML=out+esc(t.slice(at))});'''
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>LuxeStays Build Handbook</title><style>'+style+'</style></head><body><header><p class="eyebrow">Build-along course · reviewed 14 September 2026</p><h1>Build LuxeStays,<br>one working stage at a time.</h1><p>From your first Dart value to a mock-backed hotel booking app. Complete source files, checkpoints and honest provider boundaries. Flutter 3.47.4 · Dart 3.13.3.</p></header><main><nav id="contents" aria-label="Table of contents"><h2>Course map</h2><p>Work in a fresh practice directory. Each stage depends on the one before it. Code marked complete replaces the whole named file; temporary examples are explicitly identified. Source blocks are embedded here, so this document needs no internet to read or copy.</p><ol>'+''.join(f'<li><a href="#stage-{i}">{html.escape(t)}</a></li>' for i,(t,_) in enumerate(chapters,1))+'</ol><a href="#glossary">Glossary</a> · <a href="#checklist">Final checklist</a></nav>'+''.join(text for _,text in chapters)+end+'</main><footer>LuxeStays · Source-complete learning edition · Synthetic services and data</footer><script>'+script+'</script></body></html>'
OUT.write_text(page)
(ROOT / 'docs/LuxeStays-Build-Handbook.html').write_text(page)
print(f'Generated {OUT}: {len(chapters)} stages; {len(included)} embedded source files; {len(page):,} characters.')
